server:
  port: 7777
  servlet:
    session:
#      timeout: 10  #로그인 세션 타임아웃 : 10초
      timeout: 180m  #로그인 세션 타임아웃 : 180분
      cookie:
        max-age: 180m
        http-only: true

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/firewall_manager
    username: sa
    password: asdasd
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  #주의
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace